[tools]
age = "latest"
bat = "latest"
btop = "latest"
duf = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
k9s = "latest"
kubectl = "latest"
node = "latest"
rg = "latest"
sops = "latest"
task = "latest"
uv = "latest"
yt-dlp = "latest"
zoxide = "latest"
"aqua:budimanjojo/talhelper" = "latest"
"aqua:fluxcd/flux2" = "latest"
"aqua:helm/helm" = "latest"
"aqua:helmfile/helmfile" = "latest"
"aqua:mikefarah/yq" = "latest"
"aqua:siderolabs/talos" = "latest"
"aqua:yannh/kubeconform" = "latest"
